### ISSUE TITLE
Update readme with play store button

### ISSUE THREAD

**Issue by DLMousey** [DLMousey/shopping-list-app#16]
Users need to be able to find the app on the play store, given it's not remotely search ranked (because I'm too lazy/apathetic to bother SEOing it's listing) a button needs to be added to the readme with a link to the play store.

Ideally the official "available on Google play" one

**Comment by codea-holic** [comment]
Hey @DLMousey, I would like to contribute to this project. Can you please give me details about this issue?

**Comment by DLMousey** [comment]
The readme at the root of the repo needs one of those "Get it on google play" badges that links to the store like this 
![image](https://user-images.githubusercontent.com/8281699/122994386-4e7d6180-d3a0-11eb-93b8-34582787fd6c.png)

It'll need to link to the main play store listing here - https://play.google.com/store/apps/details?id=com.enderstudy.shoppinglist
