### ISSUE TITLE
Add confirmation prompt when selecting the "clear list" button

### ISSUE THREAD

**Issue by stinja** [DLMousey/shopping-list-app#19]
The "Clear List" and "Add All to Cart" options are very close together. It would be easy to accidentally hit "Clear List" when you actually mean to "Add All to Cart". A good solution would be to add a prompt asking the user to confirm they would like to clear the list.

 Perhaps with some fun added wording:
 
  All done with your shopping and ready to clear your list? 
    <Yes, Clear the list!> <No, I want to keep my list.>

Add green to Yes option, and red to No option for visibility sake and good UI.

If you don't like this suggestion, please move the clear list option to the three dots or to another area of the screen away from the "Add All to Cart" button.

**Comment by stinja** [comment]
Looks like this was fixed in the latest update. Woot.

**Comment by DLMousey** [comment]
Accidentally fixed in 932646d65592b86e238bdc2382df2775264f90b5 :tada:
